### ISSUE TITLE
Bug - https://forests.nfa.go.ug/plans/.....

### ISSUE THREAD

**Issue by LeScruf** [National-Forestry-Authority/forests#205]
@pcambra this part of the system seems to be missing - needs to be fixed (unless it's being worked on).

**Comment by pcambra** [comment]
@LeScruf  thanks for reporting! I think this is mixed between the PHP version (we're still on 7.4 because farmos just updated to PHP 8 https://www.drupal.org/project/farm/issues/3186530) and we need to catch up, we will deal with it from both the site perspective /c @peacog  and the server side.

**Comment by LeScruf** [comment]
No problem - just spinning back up this end ...

**Comment by peacog** [comment]
@LeScruf we've fixed the plans page. The problem was that we had overridden the route to use layout builder in the layout builder route settings here: https://forests.nfa.go.ug/admin/config/content/layout-builder-routing. We've removed the plans page from the settings so the page is back to its default view.

**Comment by LeScruf** [comment]
Thanks!
