### ISSUE TITLE
New widget to reference sectors and CFRs on plans

### ISSUE THREAD

**Issue by ygoex** [National-Forestry-Authority/forests#312]
We need a new checkbox field on the plan entity (forest management area plan).

If checkbox is not selected, we show the current widget for CFRs.
If the checkbox is selected, we show a dependant widget that allows the user to select the sector first, and then the CFRs that belong to the sector with checkboxes. This widget saves on the current CFR field.

When editing, if the forest management area plan checkbox is selected we show the new widget and calculate the sector by looking at the CFRs and look where it belongs.

**Comment by ygoex** [comment]
For both the current and new widgets for CFRs we need to restrict selectable CFRs to those not already used or those that belong to plans that are archived.

**Comment by pcambra** [comment]
@peacog There's a new PR to review that includes an initial version of the widget we've described.

Had to make some concessions due to the change of CFRs to be checkboxes rather than autocompletes.

We don't have a FMAP checkbox that changes modes, we always go for Sector + CFRs on the widget, but the data saved is the same as it was, so changes are at the form level only.

And to make everything very consistent, once you've selected a sector, you can add/remove CFRs *but you can't change a plan from sector*

<img width="989" alt="image" src="https://github.com/National-Forestry-Authority/forests/assets/104912/c2c5f62a-9d81-410c-b9f9-7ac39b8c719a">

**Comment by pcambra** [comment]
Pending: "restrict selectable CFRs to those not already used or those that belong to plans that are archived."

**Comment by peacog** [comment]
I tested it and it's perfect @pcambra. I'll hold off on merging until the pending CFR filtering is done. Thanks!

**Comment by pcambra** [comment]
@peacog thanks!, the selectable restriction is now implemented at two levels, I've changed the constraint from Unique to a custom one that looks for assets in plans that are also not archived.
Additionally, the form will grey out the assets used in not archived plans:

<img width="605" alt="image" src="https://github.com/National-Forestry-Authority/forests/assets/104912/a06f0930-4051-476d-91a8-2f94b2b5c25f">

**Comment by peacog** [comment]
This is ready to test @LeScruf

**Comment by LeScruf** [comment]
Looking good! Thks!
